//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.DAL
{
    using System;
    
    public partial class get_candidates_list_Result1
    {
        public string firstname { get; set; }
        public string lastname { get; set; }
        public Nullable<int> pk_resource_profile_id { get; set; }
        public string email_id { get; set; }
        public string availablity { get; set; }
        public string about_us { get; set; }
        public Nullable<int> fk_experience_level { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string experience_years { get; set; }
        public string level { get; set; }
        public string city_name { get; set; }
        public string country_name { get; set; }
        public string state_name { get; set; }
        public Nullable<bool> is_Active { get; set; }
        public string profile_pic { get; set; }
        public string contact_no { get; set; }
        public Nullable<int> pk_candidate_interested_id { get; set; }
        public string expertise { get; set; }
        public string expertise_text { get; set; }
        public Nullable<int> job_type { get; set; }
    }
}
