//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class portal_user_candidate_info
    {
        public int pk_candidate_info_id { get; set; }
        public Nullable<int> fk_user_id { get; set; }
        public string technologies { get; set; }
        public string resume { get; set; }
        public string availability { get; set; }
        public string preferred_country { get; set; }
        public string preferred_city { get; set; }
        public string preferred_state { get; set; }
        public string head_line { get; set; }
    
        public virtual portal_user portal_user { get; set; }
    }
}
