//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class portal_user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public portal_user()
        {
            this.portal_user_role_mapping = new HashSet<portal_user_role_mapping>();
            this.portal_for_interested_Candidate = new HashSet<portal_for_interested_Candidate>();
            this.portal_post_requirement = new HashSet<portal_post_requirement>();
            this.portal_user_candidate_info = new HashSet<portal_user_candidate_info>();
            this.portal_vendor_plan_mapping = new HashSet<portal_vendor_plan_mapping>();
            this.portal_vendor_lead_access_mapping = new HashSet<portal_vendor_lead_access_mapping>();
            this.portal_userplan_mapping = new HashSet<portal_userplan_mapping>();
            this.portal_plan_duration_left = new HashSet<portal_plan_duration_left>();
        }
    
        public int pk_user_id { get; set; }
        public string user_name { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string profile_pic { get; set; }
        public string about_us { get; set; }
        public string contact { get; set; }
        public bool is_active { get; set; }
        public bool is_delete { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<System.DateTime> last_login_date { get; set; }
        public Nullable<int> login_count { get; set; }
        public Nullable<int> fk_country_id { get; set; }
        public Nullable<int> fk_state_id { get; set; }
        public Nullable<int> fk_city_id { get; set; }
        public bool is_paid_user { get; set; }
        public string user_hash { get; set; }
        public bool is_email_verified { get; set; }
    
        public virtual portal_city portal_city { get; set; }
        public virtual portal_country portal_country { get; set; }
        public virtual portal_state portal_state { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<portal_user_role_mapping> portal_user_role_mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<portal_for_interested_Candidate> portal_for_interested_Candidate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<portal_post_requirement> portal_post_requirement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<portal_user_candidate_info> portal_user_candidate_info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<portal_vendor_plan_mapping> portal_vendor_plan_mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<portal_vendor_lead_access_mapping> portal_vendor_lead_access_mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<portal_userplan_mapping> portal_userplan_mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<portal_plan_duration_left> portal_plan_duration_left { get; set; }
    }
}
