//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class portal_candidate_plan
    {
        public int pk_candidate_plan_id { get; set; }
        public Nullable<int> fk_plan_id { get; set; }
        public string state_listing { get; set; }
        public string city_listing { get; set; }
        public Nullable<int> lead_access_limit { get; set; }
        public string technology_limit { get; set; }
        public Nullable<int> technology_count { get; set; }
        public Nullable<int> per_technology_count { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public Nullable<System.DateTime> added_date { get; set; }
        public string country_listing_names { get; set; }
        public string state_listing_names { get; set; }
        public string city_listing_names { get; set; }
        public string custom_plan_price { get; set; }
    
        public virtual portal_plan portal_plan { get; set; }
    }
}
