//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class portal_plan_duration_left
    {
        public int pk_vendor_plan_id { get; set; }
        public Nullable<int> fk_plan_id { get; set; }
        public Nullable<int> candidate_listing_limit { get; set; }
        public Nullable<int> interest_recived_limit { get; set; }
        public Nullable<int> lead_access_limit { get; set; }
        public string technology_limit { get; set; }
        public Nullable<int> technology_count { get; set; }
        public string per_technology_count { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public Nullable<System.DateTime> added_date { get; set; }
        public Nullable<double> custom_plan_price { get; set; }
        public Nullable<int> plan_duration_type { get; set; }
        public Nullable<int> fk_role_id { get; set; }
        public Nullable<int> bold_listing { get; set; }
        public Nullable<int> top_ranking { get; set; }
        public string updated_top_ranking { get; set; }
        public Nullable<int> portal_userplan_id { get; set; }
        public Nullable<int> fk_user_id { get; set; }
    
        public virtual portal_vendor_plan portal_vendor_plan { get; set; }
        public virtual portal_user portal_user { get; set; }
        public virtual portal_role portal_role { get; set; }
        public virtual portal_vendor_plan portal_vendor_plan1 { get; set; }
    }
}
