//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class portal_user_role_mapping
    {
        public int pk_user_role_id { get; set; }
        public Nullable<int> fk_role_id { get; set; }
        public Nullable<int> fk_user_id { get; set; }
    
        public virtual portal_role portal_role { get; set; }
        public virtual portal_user portal_user { get; set; }
    }
}
