//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class portal_vendor_plan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public portal_vendor_plan()
        {
            this.portal_vendor_plan_mapping = new HashSet<portal_vendor_plan_mapping>();
            this.portal_userplan_mapping = new HashSet<portal_userplan_mapping>();
            this.portal_plan_duration_left = new HashSet<portal_plan_duration_left>();
            this.portal_plan_duration_left1 = new HashSet<portal_plan_duration_left>();
        }
    
        public int pk_vendor_plan_id { get; set; }
        public Nullable<int> fk_plan_id { get; set; }
        public Nullable<int> candidate_listing_limit { get; set; }
        public Nullable<int> interest_recived_limit { get; set; }
        public string country_listing { get; set; }
        public string state_listing { get; set; }
        public string city_listing { get; set; }
        public Nullable<int> lead_access_limit { get; set; }
        public string technology_limit { get; set; }
        public Nullable<int> technology_count { get; set; }
        public Nullable<int> per_technology_count { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public Nullable<System.DateTime> added_date { get; set; }
        public string country_listing_names { get; set; }
        public string state_listing_names { get; set; }
        public string city_listing_names { get; set; }
        public double custom_plan_price { get; set; }
        public Nullable<int> plan_duration_type { get; set; }
        public Nullable<int> fk_role_id { get; set; }
        public Nullable<int> bold_listing { get; set; }
        public Nullable<int> top_ranking { get; set; }
    
        public virtual portal_plan portal_plan { get; set; }
        public virtual portal_role portal_role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<portal_vendor_plan_mapping> portal_vendor_plan_mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<portal_userplan_mapping> portal_userplan_mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<portal_plan_duration_left> portal_plan_duration_left { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<portal_plan_duration_left> portal_plan_duration_left1 { get; set; }
    }
}
