//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class portal_post_requirement
    {
        public int pk_requirement_id { get; set; }
        public string requirement_title { get; set; }
        public string fullname { get; set; }
        public string email_id { get; set; }
        public string mobile_no { get; set; }
        public string message { get; set; }
        public string subject { get; set; }
        public Nullable<System.DateTime> added_date { get; set; }
        public int approved_status { get; set; }
        public string status_reason { get; set; }
        public Nullable<int> fk_client_id { get; set; }
        public string project_type { get; set; }
        public string client_reason { get; set; }
        public string image { get; set; }
        public Nullable<int> status_by_codelate { get; set; }
    
        public virtual portal_user portal_user { get; set; }
    }
}
