//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class portal_what_client_says
    {
        public int pk_client_what_says_id { get; set; }
        public string title { get; set; }
        public string discription { get; set; }
        public string client_name { get; set; }
        public Nullable<System.DateTime> added_datetime { get; set; }
        public Nullable<bool> is_published_by_admin { get; set; }
        public string image { get; set; }
    }
}
